// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpx6LzpNkOgdGj4CjVEmsD9qGtO9I8LHQ',
    appId: '1:475953012346:web:3aec2fac70c7742423a5c3',
    messagingSenderId: '475953012346',
    projectId: 'hangout-sales-app',
    authDomain: 'hangout-sales-app.firebaseapp.com',
    storageBucket: 'hangout-sales-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyK8g_jmSOcsGyBigvsMDdPxLo1f16ryA',
    appId: '1:475953012346:android:7b2d861ba14c365623a5c3',
    messagingSenderId: '475953012346',
    projectId: 'hangout-sales-app',
    storageBucket: 'hangout-sales-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2uS1VKc6D6VRaF9YuOKBYDh2e4863Uhs',
    appId: '1:475953012346:ios:10cb597c5982d64c23a5c3',
    messagingSenderId: '475953012346',
    projectId: 'hangout-sales-app',
    storageBucket: 'hangout-sales-app.firebasestorage.app',
    iosBundleId: 'com.example.hangoutSalesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2uS1VKc6D6VRaF9YuOKBYDh2e4863Uhs',
    appId: '1:475953012346:ios:10cb597c5982d64c23a5c3',
    messagingSenderId: '475953012346',
    projectId: 'hangout-sales-app',
    storageBucket: 'hangout-sales-app.firebasestorage.app',
    iosBundleId: 'com.example.hangoutSalesApp',
  );
}
